#ifndef __H_KERNEL_ficticious_bobaru_n
#define __H_KERNEL_ficticious_bobaru_n

/*
 * This file was autogenerated by popcorn version 0
 * Copyright 2015-17
 * Alejandro Francisco Queiruga
 * Lawrence Berkeley National Lab
 */

#include "kernel.h"

extern kernel_t kernel_ficticious_bobaru_n;

#endif