# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_ficticious_lib')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_ficticious_lib')
    _ficticious_lib = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ficticious_lib', [dirname(__file__)])
        except ImportError:
            import _ficticious_lib
            return _ficticious_lib
        try:
            _mod = imp.load_module('_ficticious_lib', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _ficticious_lib = swig_import_helper()
    del swig_import_helper
else:
    import _ficticious_lib
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

KERNEL_MAP_MAX = _ficticious_lib.KERNEL_MAP_MAX
KERNEL_INP_MAX = _ficticious_lib.KERNEL_INP_MAX
KERNEL_OUTP_MAX = _ficticious_lib.KERNEL_OUTP_MAX
KERNEL_OUT_MAP_MAX = _ficticious_lib.KERNEL_OUT_MAP_MAX
KERNEL_NAME_MAX = _ficticious_lib.KERNEL_NAME_MAX
class inp_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, inp_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, inp_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["field_number"] = _ficticious_lib.inp_t_field_number_set
    __swig_getmethods__["field_number"] = _ficticious_lib.inp_t_field_number_get
    if _newclass:
        field_number = _swig_property(_ficticious_lib.inp_t_field_number_get, _ficticious_lib.inp_t_field_number_set)
    __swig_setmethods__["map_num"] = _ficticious_lib.inp_t_map_num_set
    __swig_getmethods__["map_num"] = _ficticious_lib.inp_t_map_num_get
    if _newclass:
        map_num = _swig_property(_ficticious_lib.inp_t_map_num_get, _ficticious_lib.inp_t_map_num_set)
    __swig_setmethods__["name"] = _ficticious_lib.inp_t_name_set
    __swig_getmethods__["name"] = _ficticious_lib.inp_t_name_get
    if _newclass:
        name = _swig_property(_ficticious_lib.inp_t_name_get, _ficticious_lib.inp_t_name_set)

    def __init__(self):
        this = _ficticious_lib.new_inp_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _ficticious_lib.delete_inp_t
    __del__ = lambda self: None
inp_t_swigregister = _ficticious_lib.inp_t_swigregister
inp_t_swigregister(inp_t)

class outp_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, outp_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, outp_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["rank"] = _ficticious_lib.outp_t_rank_set
    __swig_getmethods__["rank"] = _ficticious_lib.outp_t_rank_get
    if _newclass:
        rank = _swig_property(_ficticious_lib.outp_t_rank_get, _ficticious_lib.outp_t_rank_set)
    __swig_setmethods__["nmap"] = _ficticious_lib.outp_t_nmap_set
    __swig_getmethods__["nmap"] = _ficticious_lib.outp_t_nmap_get
    if _newclass:
        nmap = _swig_property(_ficticious_lib.outp_t_nmap_get, _ficticious_lib.outp_t_nmap_set)
    __swig_setmethods__["map_nums"] = _ficticious_lib.outp_t_map_nums_set
    __swig_getmethods__["map_nums"] = _ficticious_lib.outp_t_map_nums_get
    if _newclass:
        map_nums = _swig_property(_ficticious_lib.outp_t_map_nums_get, _ficticious_lib.outp_t_map_nums_set)
    __swig_setmethods__["name"] = _ficticious_lib.outp_t_name_set
    __swig_getmethods__["name"] = _ficticious_lib.outp_t_name_get
    if _newclass:
        name = _swig_property(_ficticious_lib.outp_t_name_get, _ficticious_lib.outp_t_name_set)

    def __init__(self):
        this = _ficticious_lib.new_outp_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _ficticious_lib.delete_outp_t
    __del__ = lambda self: None
outp_t_swigregister = _ficticious_lib.outp_t_swigregister
outp_t_swigregister(outp_t)

class kernel_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, kernel_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, kernel_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nmap"] = _ficticious_lib.kernel_t_nmap_set
    __swig_getmethods__["nmap"] = _ficticious_lib.kernel_t_nmap_get
    if _newclass:
        nmap = _swig_property(_ficticious_lib.kernel_t_nmap_get, _ficticious_lib.kernel_t_nmap_set)
    __swig_setmethods__["maps"] = _ficticious_lib.kernel_t_maps_set
    __swig_getmethods__["maps"] = _ficticious_lib.kernel_t_maps_get
    if _newclass:
        maps = _swig_property(_ficticious_lib.kernel_t_maps_get, _ficticious_lib.kernel_t_maps_set)
    __swig_setmethods__["ninp"] = _ficticious_lib.kernel_t_ninp_set
    __swig_getmethods__["ninp"] = _ficticious_lib.kernel_t_ninp_get
    if _newclass:
        ninp = _swig_property(_ficticious_lib.kernel_t_ninp_get, _ficticious_lib.kernel_t_ninp_set)
    __swig_setmethods__["inp"] = _ficticious_lib.kernel_t_inp_set
    __swig_getmethods__["inp"] = _ficticious_lib.kernel_t_inp_get
    if _newclass:
        inp = _swig_property(_ficticious_lib.kernel_t_inp_get, _ficticious_lib.kernel_t_inp_set)
    __swig_setmethods__["noutp"] = _ficticious_lib.kernel_t_noutp_set
    __swig_getmethods__["noutp"] = _ficticious_lib.kernel_t_noutp_get
    if _newclass:
        noutp = _swig_property(_ficticious_lib.kernel_t_noutp_get, _ficticious_lib.kernel_t_noutp_set)
    __swig_setmethods__["outp"] = _ficticious_lib.kernel_t_outp_set
    __swig_getmethods__["outp"] = _ficticious_lib.kernel_t_outp_get
    if _newclass:
        outp = _swig_property(_ficticious_lib.kernel_t_outp_get, _ficticious_lib.kernel_t_outp_set)
    __swig_setmethods__["name"] = _ficticious_lib.kernel_t_name_set
    __swig_getmethods__["name"] = _ficticious_lib.kernel_t_name_get
    if _newclass:
        name = _swig_property(_ficticious_lib.kernel_t_name_get, _ficticious_lib.kernel_t_name_set)
    __swig_setmethods__["eval"] = _ficticious_lib.kernel_t_eval_set
    __swig_getmethods__["eval"] = _ficticious_lib.kernel_t_eval_get
    if _newclass:
        eval = _swig_property(_ficticious_lib.kernel_t_eval_get, _ficticious_lib.kernel_t_eval_set)

    def __init__(self):
        this = _ficticious_lib.new_kernel_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _ficticious_lib.delete_kernel_t
    __del__ = lambda self: None
kernel_t_swigregister = _ficticious_lib.kernel_t_swigregister
kernel_t_swigregister(kernel_t)


def kernel_outps_len(ke, l_edge):
    return _ficticious_lib.kernel_outps_len(ke, l_edge)
kernel_outps_len = _ficticious_lib.kernel_outps_len

def kernel_outp_len(ke, ou, l_edge):
    return _ficticious_lib.kernel_outp_len(ke, ou, l_edge)
kernel_outp_len = _ficticious_lib.kernel_outp_len

def kernel_inps_len(ke, l_edge):
    return _ficticious_lib.kernel_inps_len(ke, l_edge)
kernel_inps_len = _ficticious_lib.kernel_inps_len

def kernel_outp_ndof(ke, ou, l_edge):
    return _ficticious_lib.kernel_outp_ndof(ke, ou, l_edge)
kernel_outp_ndof = _ficticious_lib.kernel_outp_ndof
# This file is compatible with both classic and new-style classes.

cvar = _ficticious_lib.cvar

