#ifndef __H_KERNEL_bond_pressure
#define __H_KERNEL_bond_pressure

/*
 * This file was autogenerated by popcorn version 0
 * Copyright 2015-17
 * Alejandro Francisco Queiruga
 * Lawrence Berkeley National Lab
 */

#include "kernel.h"

extern kernel_t kernel_bond_pressure;

#endif