#ifndef __H_KERNEL_line_intersection
#define __H_KERNEL_line_intersection

/*
 * This file was autogenerated by popcorn version 0
 * Copyright 2015-17
 * Alejandro Francisco Queiruga
 * Lawrence Berkeley National Lab
 */

#include "kernel.h"

extern kernel_t kernel_line_intersection;

#endif