#ifndef __H_KERNEL_Fstab_Littlewood2011minus_quarticA
#define __H_KERNEL_Fstab_Littlewood2011minus_quarticA

/*
 * This file was autogenerated by popcorn version 0
 * Copyright 2015-17
 * Alejandro Francisco Queiruga
 * Lawrence Berkeley National Lab
 */

#include "kernel.h"

extern kernel_t kernel_Fstab_Littlewood2011minus_quarticA;

#endif