#ifndef __H_KERNEL_Oterkus2_rational_2_2
#define __H_KERNEL_Oterkus2_rational_2_2

/*
 * This file was autogenerated by popcorn version 0
 * Copyright 2015-17
 * Alejandro Francisco Queiruga
 * Lawrence Berkeley National Lab
 */

#include "kernel.h"

extern kernel_t kernel_Oterkus2_rational_2_2;

#endif