#ifndef __H_KERNEL_Silling_cubic
#define __H_KERNEL_Silling_cubic

/*
 * This file was autogenerated by popcorn version 0
 * Copyright 2015-17
 * Alejandro Francisco Queiruga
 * Lawrence Berkeley National Lab
 */

#include "kernel.h"

extern kernel_t kernel_Silling_cubic;

#endif