#ifndef __H_KERNEL_smooth_inv
#define __H_KERNEL_smooth_inv

/*
 * This file was autogenerated by popcorn version 0
 * Copyright 2015-17
 * Alejandro Francisco Queiruga
 * Lawrence Berkeley National Lab
 */

#include "kernel.h"

extern kernel_t kernel_smooth_inv;

#endif